Using TensorFlow backend.
/home/2014313303/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
zero : 
39451

one : 
9019
hbase-CAST
all data

Sentence length Average : 88

Under 10 : 7234
Over 10, Under 200 : 35282
Over 200, Under 400 : 3981
Over 400 : 1973

hbase-CAST
updated_train_data

Sentence length Average : 77

Under 10 : 0
Over 10, Under 200 : 30861
Over 200, Under 400 : 3677
Over 400 : 0


Test_zero:  2982
Train_zero:  26968
zero:  29950
Test_one:  804
Train_one:  7570
one:  8374


Test accuracy: 77.25295214418894

data size :  16750

zero :  8376

one :  8374

train_zero :  7571

train_one :  7570

test_zero :  805

test_one :  804

choose_zero :  649

choose_one :  960

F1score :  0.7925170068027211

AUC : 0.8802918636630512

Confusion Matrix
[[544 261]
 [105 699]]
True label 0
0.675776397515528  
0.3242236024844721  
True label 1
0.13059701492537312  
0.8694029850746269  
Traceback (most recent call last):
  File "AdaBoost_Logging.py", line 507, in <module>
    TP_file_name = "Code_snippet/real_final/"+str(test_rate)+"/TP_"+filename+"_ep"+str(ep+1)+"_"+str(count)+".txt"
NameError: name 'ep' is not defined
