Using TensorFlow backend.
/home/2014313303/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
zero : 
39451

one : 
9019
hbase-AST
all data

Sentence length Average : 35

Under 10 : 21694
Over 10, Under 200 : 25475
Over 200, Under 400 : 1121
Over 400 : 180

hbase-AST
updated_train_data

Sentence length Average : 58

Under 10 : 0
Over 10, Under 200 : 22839
Over 200, Under 400 : 1085
Over 400 : 0


Test_zero:  1851
Train_zero:  16713
zero:  18564
Test_one:  763
Train_one:  7211
one:  7974


Test accuracy: 72.4950884086444

data size :  15950

zero :  7976

one :  7974

train_zero :  7212

train_one :  7211

test_zero :  764

test_one :  763

choose_zero :  766

choose_one :  761

F1score :  0.7244094488188977

AUC : 0.822569356288555

Confusion Matrix
[[555 209]
 [211 552]]
True label 0
0.7264397905759162  
0.27356020942408377  
True label 1
0.2765399737876802  
0.7234600262123198  
Traceback (most recent call last):
  File "AdaBoost_Logging_ye.py", line 503, in <module>
    train_result = hist.history
NameError: name 'hist' is not defined
