Using TensorFlow backend.
/home/2014313303/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
zero : 
39451

one : 
9019
hbase-CAST
all data

Sentence length Average : 88

Under 10 : 7234
Over 10, Under 200 : 35282
Over 200, Under 400 : 3981
Over 400 : 1973

hbase-CAST
updated_train_data

Sentence length Average : 83

Under 10 : 0
Over 10, Under 200 : 31184
Over 200, Under 400 : 4247
Over 400 : 0


Test_zero:  3082
Train_zero:  27814
zero:  30896
Test_one:  805
Train_one:  7617
one:  8422


Test accuracy: 76.41216635630043

data size :  16846

zero :  8424

one :  8422

train_zero :  7618

train_one :  7617

test_zero :  806

test_one :  805

choose_zero :  748

choose_one :  863

F1score :  0.7721822541966427

AUC : 0.8776936948044943

Confusion Matrix
[[587 219]
 [161 644]]
True label 0
0.728287841191067  
0.271712158808933  
True label 1
0.2  
0.8  
Traceback (most recent call last):
  File "AdaBoost_Logging_ye.py", line 503, in <module>
    train_result = hist.history
NameError: name 'hist' is not defined
