Using TensorFlow backend.
/home/2014313303/.local/lib/python3.5/site-packages/sklearn/utils/validation.py:752: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
zero : 
39451

one : 
9019
hbase-code
all data

Sentence length Average : 55

Under 10 : 8165
Over 10, Under 200 : 37669
Over 200, Under 400 : 2147
Over 400 : 489

hbase-code
updated_train_data

Sentence length Average : 50

Under 10 : 0
Over 10, Under 200 : 27203
Over 200, Under 400 : 820
Over 400 : 0


Test_zero:  2300
Train_zero:  20480
zero:  22780
Test_one:  797
Train_one:  7543
one:  8340


Test accuracy: 70.34482758620689

data size :  16682

zero :  8342

one :  8340

train_zero :  7544

train_one :  7543

test_zero :  798

test_one :  797

choose_zero :  871

choose_one :  724

F1score :  0.6890203813280736

AUC : 0.810210909959969

Confusion Matrix
[[598 200]
 [273 524]]
True label 0
0.7493734335839599  
0.2506265664160401  
True label 1
0.342534504391468  
0.657465495608532  
Traceback (most recent call last):
  File "AdaBoost_Logging.py", line 507, in <module>
    TP_file_name = "Code_snippet/real_final/"+str(test_rate)+"/TP_"+filename+"_ep"+str(ep+1)+"_"+str(count)+".txt"
NameError: name 'ep' is not defined
