Using TensorFlow backend.
WARNING:tensorflow:From /home/2014313303/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py:3368: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
/home/2014313303/taeha/JavaAutoLogging/model.py:44: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=Tensor("ou..., inputs=[<tf.Tenso...)`
  model = Model(input=[input1, input2], output=output)
First data
zero :  10049
one :  10279

Second data
zero :  10049
one :  10279

hbase-code
After set document size of train data, the number of zero and one label data :  499 501
After set document size of test data, the number of zero and one label data :  9550 9778

Sentence length Average : 44

Under 10 : 3104
Over 10, Under 30 : 7785
Over 30, Under 100 : 7330
Over 100, Under 150 : 1113
Over 150, Under 200 : 509
Over 200, Under 400 : 487
Over 400 : 0

After balance out data.
hbase-code

Sentence length Average : 44

Under 10 : 3104
Over 10, Under 30 : 7785
Over 30, Under 100 : 7330
Over 100, Under 150 : 1113
Over 150, Under 200 : 509
Over 200, Under 400 : 487
Over 400 : 0

300
hbase-AST
After set document size of train data, the number of zero and one label data :  499 501
After set document size of test data, the number of zero and one label data :  9550 9778
After balance out data.
hbase-AST

Sentence length Average : 30

Under 10 : 7492
Over 10, Under 30 : 6294
Over 30, Under 100 : 5232
Over 100, Under 150 : 774
Over 150, Under 200 : 347
Over 200, Under 400 : 186
Over 400 : 3

621
Traceback (most recent call last):
  File "stacking.py", line 421, in <module>
    model.load_weights(model_h5, by_name=True)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1158, in load_weights
    reshape=reshape)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 1017, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #17 (named "dense_1"), weight <tf.Variable 'dense_1/kernel:0' shape=(256, 128) dtype=float32_ref> has shape (256, 128), but the saved weight has shape (256, 256).
